version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dst_server
    restart: always
    privileged: true
    volumes:
      - ./config:/root/.klei/DoNotStarveTogether/MyDediServer
      - ./volumes/mods:/root/dst/mods
      - ./volumes/ugc_mods:/root/dst/ugc_mods
    ports:
      - "10999:10999/udp"
      - "10998:10998/udp"
