version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dst_server
    restart: always
    volumes:
      - ./config:/root/.klei/DoNotStarveTogether/MyDediServer
      - ./mods:/root/DST/mods

volumes:
  dst_save: