version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dst_server
    restart: always
    volumes:
      - dst_save:/root/.klei/DoNotStarveTogether/Cluster_1

volumes:
  dst_save: